name: Android CI on Push and PR to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 4.0

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3
      #   with:
      #     cmdline-tools-version: 9123335

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          gradle wrapper
          gradle assembleRelease
