name: Android CI on Push and PR to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle 7.0.2
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: " 7.0.2" # Quotes required to prevent YAML converting to number

      - name: Build with Gradle  7.0.2
        run: |
          ls -al
          gradle build

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3
      #   with:
      #     cmdline-tools-version: 9123335

      # - name: Build with Gradle
      #   run: |
      #     chmod +x gradlew
      #     gradle wrapper
      #     gradle assembleRelease
